apiVersion: apps/v1
kind: Deployment
metadata:
  name: UI-app
  labels:
    app: UI
    env: dev
spec:
  replicas: 2
  selector:
    matchLabels:
      app: UI
  template:
    metadata:
      labels:
        app: UI
        env: dev
    spec:
      containers:
        - name: UI
          image: rakesh556575/utap:ui
          ports:
            - name:  http
              containerPort: 8080
              protocol: TCP