name: deploy-auth

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - run: docker login -u $DOCKER_USERNAME -p $DOCKER_PASSWORD
        env:
            DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
            DOCKER_PASSWORD: ${{ secrets.DOCKERHUB_PASSWORD }}
      - uses: actions/checkout@v2
      - run: docker build -t rakesh556575/utap:UI .

      - run: docker push rakesh556575/utap:UI
