name: ci

on:
  push:
    branches: master

jobs:
  Build:
    runs-on: ubuntu-latest
    env:
      version: 6
    steps:


      -
        name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      - uses: actions/checkout@v2
      - run: cd uiapp && docker build -t rakesh556575/ui:vers${{ env.version }} .
      - run: docker push  rakesh556575/ui:vers${{env.version}}
      - run: echo '${{ secrets.AZURE_CREDENTIALS }}'
      - uses: Azure/aks-set-context@v1
        with:
          creds: '${{ secrets.AZURE_CREDENTIALS }}'
          cluster-name: UTAP
          resource-group: DefaultResourceGroup-EUS
      - uses: Azure/k8s-deploy@v1
        with:
            manifests: |
              manifests/deployment.yaml
              manifests/service.yaml
              manifests/ingresssvc.yaml

