name: ci

on:
  push:
    branches: master

jobs:
  Build:
    runs-on: ubuntu-latest
    steps:
      -
        name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      - run: cd UTAP && docker build -t rakesh556575/utap:ui .
      - run: docker push -t rakesh556575/utap:ui

